### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by jakechai** [zhiselfly/ComfyUI-Alimama-ControlNet-compatible#1]
Thanks for your work!! But I tested failed.

![allimama](https://github.com/user-attachments/assets/6c9f43b5-20f3-4602-9eab-21fd315d3075)

**Comment by jakechai** [comment]
Do I need to install https://github.com/JPlin/SD3-Controlnet-Inpainting

**Comment by jakechai** [comment]
I've tried the Alimama flux dev ControlNet inpainting alpha, it shows the same issue.

**Comment by zhiselfly** [comment]
What's your ComfyUI version?

**Comment by jakechai** [comment]
ComfyUI: 2652[0c7c98]    (2024-09-05)

**Comment by zhiselfly** [comment]
I think my version is too old.😂

**Comment by jakechai** [comment]
Please also test the new version of comfyUI if you have time. Great thanks!

**Comment by zhiselfly** [comment]
I've added compatibility for the new version. Please update my code. 
[c69bdd4](https://github.com/zhiselfly/ComfyUI-Alimama-ControlNet-compatible/commit/fed65b58593e7fb75638e16b7ba847b39f7ec454)

**Comment by zhiselfly** [comment]
The issue should now be fixed. If there is still an issue after getting the latest changes, please reopen the issue.

**Comment by jakechai** [comment]
It works!
![微信截图_20240914145715](https://github.com/user-attachments/assets/81990f2a-9572-49c9-9e53-3a26a685ab20)
![worked](https://github.com/user-attachments/assets/0c760ce7-f59d-4c50-8710-8f69a0bcb7f3)

Inpainting result is better than "outpainting"
![微信截图_20240914150747](https://github.com/user-attachments/assets/25d91cea-d889-4594-9d90-09aa2dd9e6d1)
![微信截图_20240914144801](https://github.com/user-attachments/assets/7ce10c93-43aa-4ff4-9e58-7126e7585db8)

But sometimes it went wrong: color loss or low quality output
![ComfyUI_temp_pjdyc_00007_](https://github.com/user-attachments/assets/bd79ae93-bb7d-4aab-b27a-eb8d96eed58f)
![ComfyUI_temp_pjdyc_00005_](https://github.com/user-attachments/assets/194c4c6c-f70d-4b3a-a623-4f3a26dfe335)

**Comment by jakechai** [comment]
@zhiselfly You are amazing!

**Comment by zhiselfly** [comment]
> @zhiselfly You are amazing!

I guess the reason is that the additional channel is multiplied by a factor when the built-in ControlNet of comfyUI transmits Conditionings. Go update the official comfyUI, the official one already supports it, which may avoid the above problems.
I always feel that the approach of scaling the mask and then stitching it back to the encoded features has issues. The scaling of the mask here might cause discrepancies with the repainted area, leading to potential problems. I have carefully read through the pipeline in diffusers and merely tried to translate the process as accurately as possible.
It is also possible that all my guesses are wrong. I also found that some redraws have very obvious boundaries. It may also be a model problem. These guesses still need to be verified.

**Comment by jakechai** [comment]
No, boundaries are still there when using the official Aalimama controlNet Apply node.
Thanks anyway.
